version: "3.9"

services:
  db:
    image: mongo:latest
    container_name: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=djangoadmin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
        - mongo-compose-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - db
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=djangoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data/db

  api:
    build: .
    container_name: api
    command: sh -c "python app/main.py"
    volumes:
        - .:/fastapi
    ports:
        - "8000:8000"
    networks:
        - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge